<a href="https://colab.research.google.com/github/UnknownMie/ML-Lab-Assignment-1/blob/main/ML_Lab_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

# **Assignment 1**


---


####Based on NumPy
---
## **Importing Numpy**

---



In [ ]:
import numpy as np



---
Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])



In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = np.flip(arr)
print(reversed_arr)


[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Using flatten()")
flattened_arr1 = array1.flatten()
print(flattened_arr1)

print("Using ravel()") #Value changed in array created by Ravel will
# change the initial unflattened array
flattened_arr2 = array1.ravel()
print(flattened_arr2)



Using flatten()
[1 2 3 2 4 5 1 2 3]
Using ravel()
[1 2 3 2 4 5 1 2 3]



(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

are_equal = np.array_equal(arr1, arr2)
print(are_equal)


True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
#bincount returns an array of frequqncies of numbers
#The array size will be +1 to the largest number in array
#argmax returns index of largest element of array
x = np.array([1,2,3,4,5,1,2,1,1,1])

most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)[0]

print("Most frequent value in x:", most_frequent_x)
print("Indices of most frequent value in x:", indices_x)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)[0]

print("Most frequent value in y:", most_frequent_y)
print("Indices of most frequent value in y:", indices_y)

Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),




In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


Find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [ ]:
# i. Sum of all elements
sum = np.sum(gfg)
print("Sum of all elements:", sum)

# ii. Row-wise
sumr = np.sum(gfg, axis=1)
print("Sum of all elements row-wise:", sumr)

# iii.Column-wise
sumc = np.sum(gfg, axis=0)
print("Sum of all elements column-wise:", sumc)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal elements
sum_diagonal_elements = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal_elements)

# ii. Eigen values of matrix
eigenvalues = np.linalg.eigvals(n_array)
print("Eigen values of matrix:", eigenvalues)

# iii. Eigen vectors of matrix
_, eigenvectors = np.linalg.eig(n_array)
print("Eigen vectors of matrix:")
print(eigenvectors)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:")
print(inverse_matrix)

# v. Determinant of matrix
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)


Sum of diagonal elements: 176
Eigen values of matrix: [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]



In [ ]:

# i.
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

result_matrix = np.dot(p, q)
print("Matrix multiplication result:")
print(result_matrix)

covariance_matrix = np.cov(result_matrix.T)
print("Covariance between matrices:")
print(covariance_matrix)

# ii.
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

result_matrix2 = np.dot(p2, q2)
print("Matrix multiplication result:")
print(result_matrix2)

covariance_matrix2 = np.cov(result_matrix2.T)
print("Covariance between matrices:")
print(covariance_matrix2)


Matrix multiplication result:
[[16 19]
 [26 31]]
Covariance between matrices:
[[50. 60.]
 [60. 72.]]
Matrix multiplication result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between matrices:
[[233.33333333 280.          70.        ]
 [280.         336.          84.        ]
 [ 70.          84.          21.        ]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner_product = np.inner(x, y)
print("Inner product:")
print(inner_product)

# Outer product
outer_product = np.outer(x, y)
print("Outer product:")
print(outer_product)

# Cartesian product
cartesian_product = np.kron(x, y)
print("Cartesian product:")
print(cartesian_product)

Inner product:
[[17 52]
 [13 62]]
Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[ 2 10  0  3 15  0  4 20  0]
 [10 20  6 15 30  9 20 40 12]
 [ 3 15  0  2 10  0  9 45  0]
 [15 30  9 10 20  6 45 90 27]]




---
Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])




In [ ]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

i. Find element-wise absolute value

In [ ]:
absolute_value_array = np.abs(array)
print("Element-wise absolute value:")
print(absolute_value_array)

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]


ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.


In [ ]:
percentiles = [25, 50, 75]
flattened_array = array.flatten()

for row_idx, row in enumerate(array):
    for col_idx, col in enumerate(row):
        print(f"Percentiles for row {row_idx + 1}, column {col_idx + 1}:")
        print(np.percentile(array, percentiles))
        print("")

Percentiles for row 1, column 1:
[-3.5 -0.5  2.5]

Percentiles for row 1, column 2:
[-3.5 -0.5  2.5]

Percentiles for row 1, column 3:
[-3.5 -0.5  2.5]

Percentiles for row 2, column 1:
[-3.5 -0.5  2.5]

Percentiles for row 2, column 2:
[-3.5 -0.5  2.5]

Percentiles for row 2, column 3:
[-3.5 -0.5  2.5]



iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row


In [ ]:
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_dev_flattened = np.std(flattened_array)

print("Mean of flattened array:", mean_flattened)
print("Median of flattened array:", median_flattened)
print("Standard Deviation of flattened array:", std_dev_flattened)

for axis in [0, 1]:
    print(f"Axis {axis} statistics:")
    print("Mean:", np.mean(array, axis=axis))
    print("Median:", np.median(array, axis=axis))
    print("Standard Deviation:", np.std(array, axis=axis))
    print("")


Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224
Axis 0 statistics:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Axis 1 statistics:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]




(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Original Array:", a)
print("Floor Values:", floor_values)
print("Ceiling Values:", ceiling_values)
print("Truncated Values:", truncated_values)
print("Rounded Values:", rounded_values)

Original Array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor Values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]




---
Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find


In [ ]:
array_a = np.array([10, 52, 62, 16, 16, 54, 453])


i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [ ]:
# i.
sorted_array_a = np.sort(array_a)
print("i. Sorted array:", sorted_array_a)

# ii.
indices_sorted_array_a = np.argsort(array_a)
print("ii. Indices of sorted array:", indices_sorted_array_a)

# iii.
smallest_elements_a = np.sort(array_a)[:4]
print("iii. 4 smallest elements:", smallest_elements_a)

# iv.
largest_elements_a = np.sort(array_a)[-5:]
print("iv. 5 largest elements:", largest_elements_a)

i. Sorted array: [ 10  16  16  52  54  62 453]
ii. Indices of sorted array: [0 3 4 1 5 2 6]
iii. 4 smallest elements: [10 16 16 52]
iv. 5 largest elements: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find



In [ ]:
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

i. Integer elements only

ii. Float elements only

In [ ]:
# i.
integer_elements_b = array_b[array_b.astype(int) == array_b]
print("i. Integer elements only:", integer_elements_b)

# ii.
float_elements_b = array_b[array_b.astype(int) != array_b]
print("ii. Float elements only:", float_elements_b)

i. Integer elements only: [1. 2. 3. 2.]
ii. Float elements only: [1.2 2.2]




---
Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [ ]:
from PIL import Image
from google.colab import files

def img_to_array(path):
    image = Image.open(path)
    image_array = np.array(image)

    if len(image_array.shape) == 3:
        np.savetxt("rgb_image.txt", image_array.reshape(-1, 3), fmt="%d")
        files.download("rgb_image.txt")
        print("RGB image pixel values saved to 'rgb_image.txt'.")

    elif len(image_array.shape) == 2:  # Grayscale image
        np.savetxt("gray_image.txt", image_array, fmt="%d")
        print("Grayscale image pixel values saved to 'gray_image.txt'.")

    else:
        print("Unsupported image format.")
#Path
image_path = "/content/Kheman.jpg"
img_to_array(image_path)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

RGB image pixel values saved to 'rgb_image.txt'.



(b) Load the saved file into jupyter notebook?

In [ ]:
#Run this code in Jupiter
loaded_array = np.loadtxt("rgb_image.txt")
print("Loaded array:")
print(loaded_array)


Loaded array:
[[210. 198. 186.]
 [211. 198. 189.]
 [212. 199. 190.]
 ...
 [ 77.  69.  58.]
 [ 76.  70.  58.]
 [ 73.  69.  57.]]
